import { query } from './db';
import { User } from './types';

/**
 * Get all users with pagination
 * Learn: LIMIT and OFFSET for pagination
 * LIMIT: max rows to return per page
 * OFFSET: rows to skip (for going to next pages)
 * Example: Page 2 with limit 10 = OFFSET 10, LIMIT 10 (skip first 10, get next 10)
 */
export async function getUsers(page: number = 1, limit: number = 10): Promise<{
  users: User[];
  total: number;
  pages: number;
}> {
  const offset = (page - 1) * limit;

  // Get total count of all users
  // Learn: COUNT(*) returns single number of matching rows
  const countResult = await query<{ count: string }>(
    'SELECT COUNT(*) as count FROM users'
  );
  const total = parseInt(countResult.rows[0].count, 10);
  const pages = Math.ceil(total / limit);

  // Get paginated users, sorted by created_at DESC (newest first)
  // Learn:
  // - ORDER BY created_at DESC sorts by newest first
  // - LIMIT limits to 10 rows
  // - OFFSET skips previous pages
  const result = await query<User>(
    `SELECT id, name, email, phone, country, created_at, updated_at 
     FROM users 
     ORDER BY created_at DESC 
     LIMIT $1 OFFSET $2`,
    [limit, offset]
  );

  return {
    users: result.rows,
    total,
    pages,
  };
}

/**
 * Get a single user by ID
 * Learn: SELECT with WHERE clause for filtering rows
 * WHERE id = $1 finds only the row with matching UUID
 */
export async function getUserById(id: string): Promise<User | null> {
  const result = await query<User>(
    `SELECT id, name, email, phone, country, created_at, updated_at 
     FROM users 
     WHERE id = $1`,
    [id]
  );

  return result.rows[0] || null;
}

/**
 * Search users by name or email
 * Learn: ILIKE for case-insensitive search
 * - '%search%' matches anywhere in the field
 * - 'search%' would match from start only
 * - ILIKE vs LIKE: ILIKE ignores case, LIKE is case-sensitive
 */
export async function searchUsers(
  searchTerm: string,
  page: number = 1,
  limit: number = 10
): Promise<{
  users: User[];
  total: number;
  pages: number;
}> {
  const offset = (page - 1) * limit;
  const search = `%${searchTerm}%`;

  // Count users matching search
  // Learn: WHERE with OR for multiple conditions
  // Searches both name AND email fields
  const countResult = await query<{ count: string }>(
    `SELECT COUNT(*) as count FROM users 
     WHERE name ILIKE $1 OR email ILIKE $1`,
    [search]
  );
  const total = parseInt(countResult.rows[0].count, 10);
  const pages = Math.ceil(total / limit);

  // Get paginated search results
  const result = await query<User>(
    `SELECT id, name, email, phone, country, created_at, updated_at 
     FROM users 
     WHERE name ILIKE $1 OR email ILIKE $1
     ORDER BY created_at DESC 
     LIMIT $2 OFFSET $3`,
    [search, limit, offset]
  );

  return {
    users: result.rows,
    total,
    pages,
  };
}

/**
 * Create a new user
 * Learn: INSERT with RETURNING
 * RETURNING * returns the inserted row back to you
 * This is safer than relying on client-side UUIDs or defaults
 */
export async function createUser(user: Omit<User, 'id' | 'created_at' | 'updated_at'>): Promise<User> {
  const { name, email, phone, country } = user;

  // INSERT VALUES (...) RETURNING *
  // Learn:
  // - VALUES inserts one row with $1, $2, $3, $4 placeholders
  // - RETURNING * returns all columns of inserted row
  // - id, created_at, updated_at auto-generated by PostgreSQL defaults
  const result = await query<User>(
    `INSERT INTO users (name, email, phone, country) 
     VALUES ($1, $2, $3, $4) 
     RETURNING id, name, email, phone, country, created_at, updated_at`,
    [name as string, email as string, phone as string | null, country as string | null]
  );

  return result.rows[0];
}

/**
 * Update an existing user
 * Learn: UPDATE with WHERE and RETURNING
 * Only updates fields that are provided (partial update)
 */
export async function updateUser(
  id: string,
  updates: Partial<Omit<User, 'id' | 'created_at' | 'updated_at'>>
): Promise<User | null> {
  const { name, email, phone, country } = updates;

  // Build dynamic UPDATE query
  // Only include fields that are actually being updated
  const setFields: string[] = [];
  const params: (string | number | null)[] = [];
  let paramNum = 1;

  if (name !== undefined) {
    setFields.push(`name = $${paramNum}`);
    params.push(name as string);
    paramNum++;
  }
  if (email !== undefined) {
    setFields.push(`email = $${paramNum}`);
    params.push(email as string);
    paramNum++;
  }
  if (phone !== undefined) {
    setFields.push(`phone = $${paramNum}`);
    params.push(phone as string | null);
    paramNum++;
  }
  if (country !== undefined) {
    setFields.push(`country = $${paramNum}`);
    params.push(country as string | null);
    paramNum++;
  }

  if (setFields.length === 0) {
    return null; // No updates provided
  }

  // Always update updated_at when any field changes
  // Learn: CURRENT_TIMESTAMP gets server time (not client time)
  setFields.push(`updated_at = CURRENT_TIMESTAMP`);
  params.push(id);

  // UPDATE users SET name = $1, email = $2, ... WHERE id = $3 RETURNING *
  const result = await query<User>(
    `UPDATE users 
     SET ${setFields.join(', ')} 
     WHERE id = $${paramNum}
     RETURNING id, name, email, phone, country, created_at, updated_at`,
    params
  );

  return result.rows[0] || null;
}

/**
 * Delete a user by ID
 * Learn: DELETE with WHERE to target specific row
 * Returns true if user was deleted, false if not found
 */
export async function deleteUser(id: string): Promise<boolean> {
  const result = await query(
    'DELETE FROM users WHERE id = $1',
    [id]
  );

  return result.rowCount === 1;
}






